version: '3'
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html/api
        ports:
            - "80:80"
        links:
            - php-fpm
        networks:
            - backend

    redis:
        container_name: redis
        build:
            context: ./redis/
            dockerfile: Dockerfile
        ports:
             - "6379:6379"
        networks:
            - backend


    pgadmin:
        image: dpage/pgadmin4
        restart: always
        container_name: pgadmin
        environment:
             - PGADMIN_DEFAULT_EMAIL=user@domain.com
             - PGADMIN_DEFAULT_PASSWORD=SuperSecret
             - PGADMIN_LISTEN_PORT=5050
        ports:
            - "5050:5050"
        networks:
            - backend


    php-fpm:
        container_name: php-fpm
        restart: always
        build:
            context: ./php-fpm
            dockerfile: Dockerfile
        expose:
            - "9000"
        volumes:
            - .:/var/www/html/api
        networks:
            - backend

    postgres:
        container_name: postgresql
        build:
            context: ./postgresql
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: dev
        networks:
           - backend

    zookeeper:
        container_name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        networks:
            - backend
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        container_name: kafka
        image: confluentinc/cp-kafka:latest
        networks:
            - backend
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    kafdrop:
        container_name: kafdrop
        image: obsidiandynamics/kafdrop:latest
        networks:
            - backend
        depends_on:
            - kafka
        ports:
            - "19000:9000"
        environment:
            KAFKA_BROKERCONNECT: kafka:29092

networks:
    backend:
        driver: bridge
